"""Graph retrieval orchestration layer for the Legal GraphRAG system.

This module implements ``GraphRetriever``, the ONLINE-path component that
turns a natural language query into structured graph evidence. It is a pure
orchestrator: it does not load embedding models, does not manage vector
indexes, and does not build or mutate the knowledge graph. It only wires
together already-existing modules (``QueryEmbedder``, ``GraphVectorStore``)
and performs deterministic, parameterized Cypher expansion around the
semantic seed nodes they return.

Pipeline
--------
query -> QueryEmbedder.embed() -> GraphVectorStore.vector_search()
      -> GraphRetriever graph expansion (BFS, bounded by max_hops)
      -> deduplication -> context formatting -> List[Dict]

Design notes
------------
* No LLM is ever asked to produce Cypher. All Cypher lives in this file as
  parameterized query templates.
* All Neo4j reads go through a single, reusable, exception-safe execution
  helper so failures are logged and degrade gracefully instead of crashing
  the online request path.
* Node ``embedding`` properties (written by ``GraphEmbeddingGenerator``) are
  stripped from every returned dictionary; they are large, are not useful to
  a downstream LLM context builder, and would bloat the response.
* Expansion maintains a single shared ``visited`` set across all seed nodes
  and hops, so the same node is never re-expanded and cycles cannot occur.
"""

from __future__ import annotations

import logging
import os
from typing import Any, Dict, List, Optional, Set, Tuple

from neo4j import Driver, GraphDatabase

from src.graph.graph_vector_store import GraphVectorStore
from src.graph.query_embedder import QueryEmbedder

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

#: Property written by GraphEmbeddingGenerator onto every node. Never
#: surfaced to callers of this retriever.
EMBEDDING_PROPERTY_KEY = "embedding"

#: Ordered candidates used to derive a human-readable display name for a
#: node when formatting context. The first present, non-empty property wins.
DISPLAY_NAME_PROPERTY_CANDIDATES: Tuple[str, ...] = (
    "name",
    "title",
    "clause_type",
    "text",
)

#: Safety cap on the number of neighbors fetched per node per hop, to bound
#: the size of Cypher expansion on densely connected nodes (e.g. a Company
#: connected to hundreds of contracts).
DEFAULT_MAX_CONNECTIONS_PER_NODE = 100

#: Parameterized single-hop expansion query. Never generated by an LLM.
_EXPAND_NODE_QUERY = """
MATCH (n)-[r]-(m)
WHERE elementId(n) = $node_id AND NOT elementId(m) IN $visited
RETURN elementId(m) AS target_id,
       labels(m) AS target_labels,
       properties(m) AS target_properties,
       type(r) AS relationship
LIMIT $limit
"""


class GraphRetriever:
    """Orchestrates semantic + graph-structural retrieval over Neo4j.

    ``GraphRetriever`` embeds a user query via an injected ``QueryEmbedder``,
    retrieves the nearest nodes via an injected ``GraphVectorStore``, then
    expands the local graph neighborhood of each seed node through bounded,
    parameterized Cypher traversal. The result is a list of plain Python
    dictionaries describing each seed node and its graph connections -
    never raw Neo4j or GraphDocument objects.

    Parameters
    ----------
    query_embedder : QueryEmbedder, optional
        Component responsible for turning a query string into an embedding
        vector. If omitted, a default ``QueryEmbedder()`` is constructed.
    graph_vector_store : GraphVectorStore, optional
        Component responsible for Neo4j vector index similarity search. If
        omitted, a default ``GraphVectorStore()`` is constructed.
    neo4j_uri : str, optional
        Bolt URI for Neo4j Aura. Falls back to the ``NEO4J_URI`` environment
        variable.
    neo4j_username : str, optional
        Neo4j username. Falls back to the ``NEO4J_USERNAME`` environment
        variable.
    neo4j_password : str, optional
        Neo4j password. Falls back to the ``NEO4J_PASSWORD`` environment
        variable.
    max_connections_per_node : int, default=100
        Upper bound on neighbors fetched per node per hop.

    Raises
    ------
    ValueError
        If Neo4j connection parameters are not supplied via arguments or
        environment variables.

    Examples
    --------
    >>> retriever = GraphRetriever()
    >>> context = retriever.retrieve("force majeure", top_k=5, max_hops=2)
    >>> retriever.close()
    """

    def __init__(
        self,
        query_embedder: Optional[QueryEmbedder] = None,
        graph_vector_store: Optional[GraphVectorStore] = None,
        neo4j_uri: Optional[str] = None,
        neo4j_username: Optional[str] = None,
        neo4j_password: Optional[str] = None,
        max_connections_per_node: int = DEFAULT_MAX_CONNECTIONS_PER_NODE,
    ) -> None:
        logger.info("Initializing GraphRetriever")

        uri = neo4j_uri or os.environ.get("NEO4J_URI")
        username = neo4j_username or os.environ.get("NEO4J_USERNAME")
        password = neo4j_password or os.environ.get("NEO4J_PASSWORD")

        if not uri or not username or not password:
            raise ValueError(
                "Neo4j connection parameters are required. Provide "
                "neo4j_uri/neo4j_username/neo4j_password explicitly or set "
                "the NEO4J_URI, NEO4J_USERNAME, NEO4J_PASSWORD environment "
                "variables."
            )

        self._driver: Driver = GraphDatabase.driver(uri, auth=(username, password))
        self._max_connections_per_node = max_connections_per_node

        self.query_embedder = query_embedder or QueryEmbedder()
        self.graph_vector_store = graph_vector_store or GraphVectorStore()

        logger.info("GraphRetriever initialized successfully")

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def retrieve(
        self,
        query: str,
        top_k: int = 10,
        max_hops: int = 1,
    ) -> List[Dict[str, Any]]:
        """Run the full retrieval pipeline for a query.

        Parameters
        ----------
        query : str
            Natural language query, e.g. ``"force majeure"``.
        top_k : int, default=10
            Number of nearest semantic nodes to seed expansion from.
        max_hops : int, default=1
            Maximum graph traversal depth from each seed node.

        Returns
        -------
        list of dict
            One entry per seed node, each with a ``connections`` list
            describing its expanded graph neighborhood. Empty list on
            failure or if no seed nodes are found.
        """
        logger.info(
            "Starting graph retrieval | query=%r top_k=%d max_hops=%d",
            query,
            top_k,
            max_hops,
        )

        embedding = self._embed_query(query)
        if embedding is None:
            return []

        seed_nodes = self._vector_search(embedding, top_k)
        if not seed_nodes:
            logger.info("No seed nodes found for query=%r", query)
            return []

        logger.info("Vector search returned %d seed nodes", len(seed_nodes))

        visited: Set[str] = {node["id"] for node in seed_nodes if "id" in node}
        connections_map = self.expand_nodes(seed_nodes, max_hops=max_hops, visited=visited)

        context = self.build_context(seed_nodes, connections_map)
        logger.info("Context generated | entries=%d", len(context))
        return context

    def search(
        self,
        query: str,
        top_k: int = 10,
        max_hops: int = 1,
    ) -> List[Dict[str, Any]]:
        """Convenience alias exposing ``retrieve`` under the generic
        ``search`` name expected by the wider retrieval API surface.

        See Also
        --------
        retrieve : Full retrieval pipeline implementation.
        """
        return self.retrieve(query, top_k=top_k, max_hops=max_hops)

    def expand_node(
        self,
        node_id: str,
        visited: Set[str],
    ) -> List[Dict[str, Any]]:
        """Expand a single node one hop via parameterized Cypher.

        Neighbors already present in ``visited`` are excluded at the query
        level. Any neighbor returned is added to ``visited`` in place, so
        callers performing multi-hop BFS never revisit or re-expand it.

        Parameters
        ----------
        node_id : str
            ``elementId`` of the node to expand.
        visited : set of str
            Mutable, shared set of already-seen ``elementId`` values. Updated
            in place with newly discovered neighbor ids.

        Returns
        -------
        list of dict
            One entry per neighbor relationship, each with keys
            ``relationship``, ``target``, ``target_label``, ``target_id``,
            and ``target_properties``. Empty list on query failure.
        """
        logger.debug("Expanding node %s", node_id)

        records = self._run_query(
            _EXPAND_NODE_QUERY,
            {
                "node_id": node_id,
                "visited": list(visited),
                "limit": self._max_connections_per_node,
            },
        )
        if records is None:
            return []

        connections: List[Dict[str, Any]] = []
        for record in records:
            target_id = record["target_id"]
            visited.add(target_id)

            properties = self._strip_embedding(record.get("target_properties") or {})
            target_labels = record.get("target_labels") or []
            target_label = target_labels[0] if target_labels else "Unknown"
            target_name = self._display_name(properties, fallback=target_id)

            connections.append(
                {
                    "relationship": record["relationship"],
                    "target": target_name,
                    "target_label": target_label,
                    "target_id": target_id,
                    "target_properties": properties,
                }
            )

        logger.debug("Node %s expanded into %d connections", node_id, len(connections))
        return connections

    def expand_nodes(
        self,
        seed_nodes: List[Dict[str, Any]],
        max_hops: int,
        visited: Set[str],
    ) -> Dict[str, List[Dict[str, Any]]]:
        """Breadth-first expansion of every seed node up to ``max_hops``.

        Connections discovered at every hop are attributed back to the
        originating seed node (the root of the traversal), so the final
        context for a seed node reflects its full multi-hop neighborhood,
        not just its immediate neighbors.

        Parameters
        ----------
        seed_nodes : list of dict
            Nodes returned by ``GraphVectorStore.vector_search``.
        max_hops : int
            Maximum traversal depth.
        visited : set of str
            Shared, mutable set of already-seen node ids. Must already
            contain the seed node ids before calling.

        Returns
        -------
        dict
            Mapping of seed node id -> list of connection dicts gathered
            across all hops.
        """
        connections_map: Dict[str, List[Dict[str, Any]]] = {
            node["id"]: [] for node in seed_nodes if "id" in node
        }

        # frontier holds (current_node_id, root_seed_id) pairs
        frontier: List[Tuple[str, str]] = [
            (node["id"], node["id"]) for node in seed_nodes if "id" in node
        ]

        for hop in range(1, max_hops + 1):
            if not frontier:
                break
            logger.debug("Expanding hop %d | frontier size=%d", hop, len(frontier))

            next_frontier: List[Tuple[str, str]] = []
            for current_id, root_id in frontier:
                neighbors = self.expand_node(current_id, visited)
                if not neighbors:
                    continue
                connections_map.setdefault(root_id, []).extend(neighbors)
                for neighbor in neighbors:
                    next_frontier.append((neighbor["target_id"], root_id))

            frontier = next_frontier

        return connections_map

    def build_context(
        self,
        seed_nodes: List[Dict[str, Any]],
        connections_map: Dict[str, List[Dict[str, Any]]],
    ) -> List[Dict[str, Any]]:
        """Format seed nodes and their expanded connections into context dicts.

        Parameters
        ----------
        seed_nodes : list of dict
            Nodes returned by ``GraphVectorStore.vector_search``.
        connections_map : dict
            Mapping of seed node id -> list of raw connection dicts, as
            produced by ``expand_nodes``.

        Returns
        -------
        list of dict
            Each entry has keys ``node_id``, ``label``, ``name``, ``score``,
            ``properties``, and ``connections`` (deduplicated).
        """
        context: List[Dict[str, Any]] = []

        for node in seed_nodes:
            node_id = node.get("id")
            if node_id is None:
                logger.warning("Skipping seed node with missing id: %s", node)
                continue

            labels = node.get("labels") or []
            label = labels[0] if labels else "Unknown"
            properties = self._strip_embedding(node.get("properties") or {})
            name = self._display_name(properties, fallback=node_id)

            raw_connections = connections_map.get(node_id, [])
            deduped_connections = self._dedupe_connections(raw_connections)

            context.append(
                {
                    "node_id": node_id,
                    "label": label,
                    "name": name,
                    "score": node.get("score", 0.0),
                    "properties": properties,
                    "connections": [
                        {
                            "relationship": conn["relationship"],
                            "target": conn["target"],
                            "target_label": conn["target_label"],
                        }
                        for conn in deduped_connections
                    ],
                }
            )

        return context

    def close(self) -> None:
        """Release the Neo4j driver and any closable injected dependencies."""
        logger.info("Closing GraphRetriever resources")

        try:
            self._driver.close()
        except Exception:
            logger.exception("Error closing Neo4j driver")

        for dependency in (self.graph_vector_store, self.query_embedder):
            close_fn = getattr(dependency, "close", None)
            if callable(close_fn):
                try:
                    close_fn()
                except Exception:
                    logger.exception("Error closing dependency %s", type(dependency).__name__)

    def __enter__(self) -> "GraphRetriever":
        return self

    def __exit__(self, exc_type, exc_val, exc_tb) -> None:
        self.close()

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _embed_query(self, query: str) -> Optional[List[float]]:
        """Embed a query string, logging and swallowing failures."""
        logger.debug("Embedding query=%r", query)
        try:
            embedding = self.query_embedder.embed(query)
        except Exception:
            logger.exception("Failed to embed query=%r", query)
            return None
        logger.debug("Query embedded | dim=%d", len(embedding))
        return embedding

    def _vector_search(self, embedding: List[float], top_k: int) -> List[Dict[str, Any]]:
        """Run vector similarity search, logging and swallowing failures."""
        logger.debug("Running vector search | top_k=%d", top_k)
        try:
            return self.graph_vector_store.vector_search(embedding, top_k)
        except Exception:
            logger.exception("Vector search failed")
            return []

    def _run_query(
        self,
        query: str,
        parameters: Dict[str, Any],
    ) -> Optional[List[Dict[str, Any]]]:
        """Execute a parameterized read query, returning records as dicts.

        Centralizes all Neo4j session handling and exception safety so no
        single failing traversal step can crash the retrieval pipeline.

        Parameters
        ----------
        query : str
            Parameterized Cypher query. Never built from user or LLM input.
        parameters : dict
            Query parameters.

        Returns
        -------
        list of dict or None
            Query results as plain dictionaries, or ``None`` on failure.
        """
        try:
            with self._driver.session() as session:
                result = session.run(query, **parameters)
                return [record.data() for record in result]
        except Exception:
            logger.exception("Neo4j query failed | query=%s | params=%s", query, parameters)
            return None

    @staticmethod
    def _strip_embedding(properties: Dict[str, Any]) -> Dict[str, Any]:
        """Return a copy of ``properties`` with the embedding vector removed."""
        if EMBEDDING_PROPERTY_KEY not in properties:
            return dict(properties)
        return {k: v for k, v in properties.items() if k != EMBEDDING_PROPERTY_KEY}

    @staticmethod
    def _display_name(properties: Dict[str, Any], fallback: str) -> str:
        """Derive a human-readable display name from node properties."""
        for candidate in DISPLAY_NAME_PROPERTY_CANDIDATES:
            value = properties.get(candidate)
            if value:
                return str(value)
        return str(fallback)

    @staticmethod
    def _dedupe_connections(connections: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Deduplicate connections by (relationship, target_id) pair."""
        seen: Set[Tuple[str, str]] = set()
        deduped: List[Dict[str, Any]] = []
        for conn in connections:
            key = (conn["relationship"], conn["target_id"])
            if key in seen:
                continue
            seen.add(key)
            deduped.append(conn)
        return deduped